sequenceDiagram
    User->>Lambda: Request
    Lambda->>APIGateway: Request
    APIGateway->>DDB: Request
    DDB->>Cognito: Request
    Cognito-->>DDB: Response
    DDB-->>APIGateway: Response
    APIGateway-->>Lambda: Response
    Lambda-->>User: Response